#! /usr/bin/env python3


# Packages
from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk
import pandas as pd


# Connect to Elasticsearch
es = Elasticsearch("http://localhost:9200")
es.info().body

# Get all movies starring Jack Nocholson, not directed by Roman Polanski
resp = es.search(
    index="movies",
    query={
            "bool": {
                "must": {
                    "match_phrase": {
                        "cast": "jack nicholson",
                    }
                },
                "filter": {"bool": {"must_not": {"match_phrase": {"director": "roman polanski"}}}},
            },
        },            
)

print(f"Found {resp['hits']['total']['value']} matching movies:")

for movie in resp["hits"]["hits"]:
    print(f"- {movie['_source']['title']}")
